max_epochs: 100
max_steps: 0
device: auto
precision: "32"
overfit_n: 0
prefetch_factor: 512
seed: 123
deterministic: true
limit_train_batches: 1.0
limit_val_batches: 1.0
enable_checkpointing: true
logger: true
